apiVersion: apps/v1              # The API version for the deployment
kind: Deployment                 # The type of the resource to create
metadata:
  name: flask-hello-world-deployment   # The name of your deployment
spec:                            # The specification of the deployment
  replicas: 2                    # The number of pods to run
  selector:
    matchLabels:
      app: flask-hello-world     # The selector to identify which pods are part of the deployment
  template:                      # The template for the pods
    metadata:
      labels:
        app: flask-hello-world   # Labels applied to all pods in the deployment, used for selecting the pods
    spec:                        # The specification of the pod template
      containers:                # The list of containers to run within the pod
      - name: flask-hello-world  # The name of the container (for reference within Kubernetes)
        image: zoeycide/flask-hello-world:latest  # The image to use for the container
        imagePullPolicy: Always
        ports:                   # The ports that the container will listen on
        - containerPort: 5000    # The port the container is configured to listen to
      imagePullSecrets:
      - name: regcred