Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "lts"
  InstallPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.4.5
  Cpu: "1" # 1 CPU
  Memory: "2048Mi" # 2 GiB of memory
  ServiceType: LoadBalancer
  ServicePort: 80
  NodePort: 32000
  ContainerPort: 8080
  AdminUser: admin
  AdminPassword: admin # Remember to change this to use a secret or other secure methods in production
Agent:
  Enabled: true
  Image: jenkins/inbound-agent
  ImageTag: "4.3-4"
  CustomJenkinsLabels: []

Persistence:
  Enabled: true
  StorageClass: jenkins-pv
  Size: 20Gi # Adjust size according to need
  Annotations: {}
  AccessMode: ReadWriteOnce
  Volumes:
  Mounts:

# ... rest of the file
