apiVersion: v1                   # The API version for the service
kind: Service                    # The type of the resource to create
metadata:
  name: flask-hello-world-service    # The name of the service
spec:                            # The specification of the service
  type: NodePort                 # The type of service, NodePort exposes the service on each Node’s IP at a static port
  selector:                      # Selects the pods to which this service applies
    app: flask-hello-world       # The selector label that matches the deployment label
  ports:                         # A list of ports to expose through the service
  - protocol: TCP                # The protocol used by the service (TCP/UDP)
    port: 80                     # The port that the service will serve on
    targetPort: 5000             # The target port on the pod to forward traffic to
